# Applying Advanced Transformations

In [1]:
#Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json

# The Task

Your task is two-fold:

I. Clean the files and combine them into one final DataFrame.

- This dataframe should have the following columns:
- Hero (Just the name of the Hero)
- Publisher
- Gender
- Eye color
- Race
- Hair color
- Height (numeric)
- Skin color
- Alignment
- Weight (numeric)
- Plus, one-hot-encoded columns for every power that appears in the dataset. E.g.:
    - Agility
    - Flight
    - Superspeed
    - etc.

Hint: There is a space in "100 kg" or "52.5 cm"

In [2]:
df = pd.read_csv('Data/superhero_info - superhero_info.csv')
df.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"

# Separating Hero and Publisher Column

In [3]:
df[['Hero','Publisher']] = df['Hero|Publisher'].str.split('|',expand=True)
df = df.drop(columns=['Hero|Publisher'])
df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics
3,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics
4,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics

# Replacing all single quotes in Measurements with double quotes

In [4]:
## use .str.replace to replace all single quotes
df['Measurements'] = df['Measurements'].str.replace("'",'"')
## Apply the json.loads to the full column
df['Measurements'] = df['Measurements'].apply(json.loads)
df['Measurements'].head()

0    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
1     {'Height': '191.0 cm', 'Weight': '65.0 kg'}
2     {'Height': '185.0 cm', 'Weight': '90.0 kg'}
3    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
4    {'Height': '193.0 cm', 'Weight': '122.0 kg'}
Name: Measurements, dtype: object

In [5]:
#Ensuring it worked
type(df.loc[0,'Measurements'])

dict

In [6]:
#convert the single "Measurements" column into 2 separate columns
weight_height = df['Measurements'].apply(pd.Series)
weight_height

       Height    Weight
0    203.0 cm  441.0 kg
1    191.0 cm   65.0 kg
2    185.0 cm   90.0 kg
3    203.0 cm  441.0 kg
4    193.0 cm  122.0 kg
..        ...       ...
458  183.0 cm   83.0 kg
459  165.0 cm   52.0 kg
460   66.0 cm   17.0 kg
461  170.0 cm   57.0 kg
462  185.0 cm   81.0 kg

[463 rows x 2 columns]

In [7]:
weight_height['Weight'] = weight_height['Weight'].str.split(' ',expand=True)[0].astype('float32')
weight_height

       Height  Weight
0    203.0 cm   441.0
1    191.0 cm    65.0
2    185.0 cm    90.0
3    203.0 cm   441.0
4    193.0 cm   122.0
..        ...     ...
458  183.0 cm    83.0
459  165.0 cm    52.0
460   66.0 cm    17.0
461  170.0 cm    57.0
462  185.0 cm    81.0

[463 rows x 2 columns]

In [8]:
weight_height['Height'] = weight_height['Height'].str.split(' ',expand=True)[0].astype('float32')
weight_height

     Height  Weight
0     203.0   441.0
1     191.0    65.0
2     185.0    90.0
3     203.0   441.0
4     193.0   122.0
..      ...     ...
458   183.0    83.0
459   165.0    52.0
460    66.0    17.0
461   170.0    57.0
462   185.0    81.0

[463 rows x 2 columns]

# Concatenate Weight_Height column to Dataframe

In [9]:
df = pd.concat((df, weight_height), axis = 1)
df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics,203.0,441.0
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics,191.0,65.0
2,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics,185.0,90.0
3,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics,203.0,441.0
4,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics,193.0,122.0

In [10]:
#Dropping Measurements column
df = df.drop(columns = 'Measurements')
df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0,90.0
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0,441.0
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0,122.0

# Adding One Hot Encoded Powers to Original Dataframe

In [11]:
#Importing new Powers Data
power = pd.read_csv("Data/superhero_powers - superhero_powers.csv")
power.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

In [12]:
#Creating a list
power['Power_List'] = power['Powers'].str.split(',')
power.head()

,hero_names,Powers,Power_List
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed","[Agility, Super Strength, Stamina, Super Speed]"
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...","[Accelerated Healing, Durability, Longevity, S..."
2,Abe Sapien,"Agility,Accelerated Healing,Cold Resistance,Du...","[Agility, Accelerated Healing, Cold Resistance..."
3,Abin Sur,Lantern Power Ring,[Lantern Power Ring]
4,Abomination,"Accelerated Healing,Intelligence,Super Strengt...","[Accelerated Healing, Intelligence, Super Stre..."

In [13]:
power_exploded = power.explode('Power_List')[['hero_names', 'Power_List']]
power_exploded

    hero_names           Power_List
0      3-D Man              Agility
0      3-D Man       Super Strength
0      3-D Man              Stamina
0      3-D Man          Super Speed
1       A-Bomb  Accelerated Healing
..         ...                  ...
665    Zatanna      Weather Control
666       Zoom          Super Speed
666       Zoom        Intangibility
666       Zoom          Time Travel
666       Zoom    Time Manipulation

[5874 rows x 2 columns]

In [14]:
cols_to_make = power_exploded['Power_List'].dropna().unique()
cols_to_make

array(['Agility', 'Super Strength', 'Stamina', 'Super Speed',
       'Accelerated Healing', 'Durability', 'Longevity', 'Camouflage',
       'Self-Sustenance', 'Cold Resistance', 'Underwater breathing',
       'Marksmanship', 'Weapons Master', 'Intelligence', 'Telepathy',
       'Immortality', 'Reflexes', 'Enhanced Sight', 'Sub-Mariner',
       'Lantern Power Ring', 'Invulnerability', 'Animation',
       'Super Breath', 'Dimensional Awareness', 'Flight', 'Size Changing',
       'Teleportation', 'Magic', 'Dimensional Travel',
       'Molecular Manipulation', 'Energy Manipulation', 'Power Cosmic',
       'Energy Absorption', 'Elemental Transmogrification',
       'Fire Resistance', 'Natural Armor', 'Heat Resistance',
       'Matter Absorption', 'Regeneration', 'Stealth', 'Power Suit',
       'Energy Blasts', 'Energy Beams', 'Heat Generation', 'Danger Sense',
       'Phasing', 'Force Fields', 'Hypnokinesis', 'Invisibility',
       'Enhanced Senses', 'Jump', 'Shapeshifting', 'Elasticity',
       'Substance Secretion', 'Enhanced Hearing', 'Adaptation', 'Gliding',
       'Natural Weapons', 'Wallcrawling', 'Vision - Thermal',
       'Power Augmentation', 'Cryokinesis', 'Duplication',
       'Weapon-based Powers', 'Fire Control', 'Enhanced Memory',
       'Energy Constructs', 'Power Absorption', 'Time Travel',
       'Enhanced Smell', 'Water Control', 'Vision - Telescopic',
       'Magnetism', 'Vision - Microscopic', 'Vision - Night',
       'Vision - Heat', 'Vision - X-Ray', 'Psionic Powers',
       'Toxin and Disease Resistance', 'Animal Attributes',
       'Animal Oriented Powers', 'Toxin and Disease Control', 'Empathy',
       'Animal Control', 'Darkforce Manipulation', 'Time Manipulation',
       'Reality Warping', 'Web Creation', 'Symbiote Costume',
       'Telekinesis', 'Levitation', 'Biokinesis', 'Sonar',
       'Enhanced Touch', 'Seismic Power', 'Energy Armor',
       'Omnilingualism', 'Radiation Immunity', 'Density Control',
       'Light Control', 'Illumination', 'Molecular Combustion',
       'Astral Travel', 'Precognition', 'Intangibility', 'Illusions',
       'Audio Control', 'Sonic Scream', 'Peak Human Condition',
       'Vision - Infrared', 'Dexterity', 'Omnitrix', 'Omnipotent',
       'Possession', 'Energy Resistance', 'Vision - Cryo', 'Mind Control',
       'Mind Blast', 'Clairvoyance', 'Probability Manipulation',
       'Death Touch', 'Electrokinesis', 'Gravity Control',
       'Technopath/Cyberpath', 'Radar Sense', 'Astral Projection',
       'Cloaking', 'Telepathy Resistance', 'Mind Control Resistance',
       'Hyperkinesis', 'Spatial Awareness', 'Radiation Control',
       'Radiation Absorption', 'Magic Resistance', 'Element Control',
       'Plant Control', 'Terrakinesis', 'Power Sense', 'Wind Control',
       'Qwardian Power Ring', 'Echolocation', 'Resurrection', 'The Force',
       'Summoning', 'Banish', 'Molecular Dissipation',
       'Electrical Transport', 'Speed Force', 'Grim Reaping',
       'Portal Creation', 'Vitakinesis', 'Projection', 'Insanity',
       'Photographic Reflexes', 'Anti-Gravity', 'Thirstokinesis',
       'Power Nullifier', 'Weather Control', 'Omnipresent', 'Omniscient',
       'Hair Manipulation', 'Nova Force', 'Odin Force', 'Phoenix Force',
       'Intuitive aptitude', 'Melting', 'Changing Armor'], dtype=object)

In [15]:
for col in cols_to_make:
    power[col] = power['Powers'].str.contains(col)
power.head()

C:\Users\Nick\anaconda3\envs\dojo-env\lib\site-packages\ipykernel_launcher.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`

,hero_names,Powers,Power_List,Agility,Super Strength,Stamina,Super Speed,Accelerated Healing,Durability,Longevity,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
0,3-D Man,"Agility,Super Strength,Stamina,Super Speed","[Agility, Super Strength, Stamina, Super Speed]",True,True,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,"Accelerated Healing,Durability,Longevity,Super...","[Accelerated Healing, Durability, Longevity, S...",False,True,True,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
2,Abe Sapien,"Agility,Accelerated Healing,Cold Resistance,Du...","[Agility, Accelerated Healing, Cold Resistance...",True,True,True,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
3,Abin Sur,Lantern Power Ring,[Lantern Power Ring],False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Abomination,"Accelerated Healing,Intelligence,Super Strengt...","[Accelerated Healing, Intelligence, Super Stre...",False,True,True,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [16]:
power = power.drop(columns = ['Powers', 'Power_List'])
power = power.rename(columns = {'hero_names': 'Hero'})
power = power.rename(columns = {'hero_names': 'Hero'})
power.head()

,Hero,Agility,Super Strength,Stamina,Super Speed,Accelerated Healing,Durability,Longevity,Camouflage,Self-Sustenance,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
0,3-D Man,True,True,True,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,A-Bomb,False,True,True,False,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
2,Abe Sapien,True,True,True,False,True,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Abin Sur,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Abomination,False,True,True,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

# Creating Final Dataframe

In [17]:
df = pd.merge(df,power, on='Hero')
df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height,Weight,...,Weather Control,Omnipresent,Omniscient,Hair Manipulation,Nova Force,Odin Force,Phoenix Force,Intuitive aptitude,Melting,Changing Armor
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0,...,False,False,False,False,False,False,False,False,False,False
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0,...,False,False,False,False,False,False,False,False,False,False
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0,90.0,...,False,False,False,False,False,False,False,False,False,False
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0,441.0,...,False,False,False,False,False,False,False,False,False,False
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0,122.0,...,False,False,False,False,False,False,False,False,False,False

# Use your combined DataFrame to answer the following questions.

- Compare the average weight of super powers who have Super Speed to those who do not.
- What is the average height of heroes for each publisher?

# Compare the average weight of super powers who have Super Speed to those who do not.

In [18]:
df.groupby('Super Speed')['Weight'].mean()

Super Speed
False    101.773582
True     129.404037
Name: Weight, dtype: float32

# What is the average height of heroes for each publisher?

In [19]:
df.groupby('Publisher')['Height'].mean()

Publisher
DC Comics            181.923920
Dark Horse Comics    176.909088
George Lucas         159.600006
Image Comics         211.000000
Marvel Comics        191.546127
Shueisha             171.500000
Star Trek            181.500000
Team Epic TV         180.750000
Unknown              178.000000
Name: Height, dtype: float32